### ISSUE TITLE
Unhandled value '28' outside enum range for ChargingReason

### ISSUE THREAD

**Issue by pbrooks29** [mk-maddin/wattpilot-HA#41]
Getting recurring errors in the HA logs about an unhandled value 28
extracted error message:
-------------------------------------------------
This error originated from a custom integration.

Logger: custom_components.wattpilot.sensor
Source: **custom_components/wattpilot/sensor.py:132**
Integration: Fronius Wattpilot (documentation)
First occurred: April 30, 2024 at 10:04:28 PM (9 occurrences)
Last logged: May 2, 2024 at 1:30:34 PM

Wattpilot - modelStatus: _async_update_validate_platform_state failed: **state 28 not within enum values**: {0: 'NotChargingBecauseNoChargeCtrlData', 1: 'NotChargingBecauseOvertemperature', 2: 'NotChargingBecauseAccessControlWait', 3: 'ChargingBecauseForceStateOn', 4: 'NotChargingBecauseForceStateOff', 5: 'NotChargingBecauseScheduler', 6: 'NotChargingBecauseEnergyLimit', 7: 'ChargingBecauseAwattarPriceLow', 8: 'ChargingBecauseAutomaticStopTestLadung', 9: 'ChargingBecauseAutomaticStopNotEnoughTime', 10: 'ChargingBecauseAutomaticStop', 11: 'ChargingBecauseAutomaticStopNoClock', 12: 'ChargingBecausePvSurplus', 13: 'ChargingBecauseFallbackGoEDefault', 14: 'ChargingBecauseFallbackGoEScheduler', 15: 'ChargingBecauseFallbackDefault', 16: 'NotChargingBecauseFallbackGoEAwattar', 17: 'NotChargingBecauseFallbackAwattar', 18: 'NotChargingBecauseFallbackAutomaticStop', 19: 'ChargingBecauseCarCompatibilityKeepAlive', 20: 'ChargingBecauseChargePauseNotAllowed', 22: 'NotChargingBecauseSimulateUnplugging', 23: 'NotChargingBecausePhaseSwitch', 24: 'NotChargingBecauseMinPauseDuration'}

**Describe the expected behavior**
There is no apparent effect or detrimental impact as far as the actual functionality 

**To Reproduce**
N/A

**What version of Home Assistant Core is installed**
Home Assistant 2023.10.0
Frontend 20231002.0 - latest 

**What version of Wattpilot integration is installed**
"wattpilot": {
      "version": "0.1.9",

**What version of Wattpilot are you using**
22KW-V2    WattPilot Go   firmware version 40.7

**Error message shown within Home Assistant log**
see above

**Diagnostics information of Wattpilot integration**
[config_entry-wattpilot-3b55bc54926ad59482acc64c23ce8639.json.txt](https://github.com/mk-maddin/wattpilot-HA/files/15195375/config_entry-wattpilot-3b55bc54926ad59482acc64c23ce8639.json.txt)

**Additional Information**
Unrecognised value '28' is ChargingReason, which is described as 'Reason why we allow charging or not right now - values are listed at: https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md -> modelStatus'.
Looking at the Solar.Wattpilot app, this code is associated with the message "Charging Stopped by OCPP backend" on the WattPilot app.
Which I suspect is newly added in the 40.7 firmware and wasn't there when the 'goecharger' code was written.
Reporting it here for your info, will also report it in the goecharger project.
https://github.com/goecharger/go-eCharger-API-v2/issues/214

**Comment by mk-maddin** [comment]
ah - nvm
just saw code 28 was already discovered as:

'NotChargingBecauseOCPPBackend=28'

**Comment by mk-maddin** [comment]
fixed in 5a8d249ae35fc7c84ca052d63f3fe1d427fedff8

**Comment by pbrooks29** [comment]
Rather than open a completely new issue, I can see you released a version 0.2.0 recently.
Could you please update the version in manifest.json, which still shows v0.1.9?
